global:
  - name: Cabal File Exists
    command: test -f excalibur.cabal
    expected_exit: 0
  - name: The Global Check
    command: ls -a .
    expected_exit: 0

per_commit:
  - name: The failing local check
    command: test -f not_a_file
    expected_exit: 0
  # - name: The format check
  #   builtin: clang-format
  #   style_file: .clang-format
