on-repository:
  - name: Cabal File Exists
    command: test -f excalibur.cabal
    expected-exit: 0
  - name: This should always pass
    command: ls -a .
    expected-exit: 0

on-commit:
  - name: Check formatting
    command: clang-format --dry-run -Werror
    expected-exit: 0
    files:
      - "**/**.c"
      - "**/**.h"
