global:
  - name: Cabal File Exists
    command: test -f excalibur.cabal
    expected_exit: 0
  - name: The Global Check
    command: ls -a .
    expected_exit: 0

per_commit:
  - name: The Local Check
    command: pwd
    expected_exit: 0
