cabal-version:       2.2

name:                excalibur
version:             0.1.1
synopsis:            A tool for running automated checks on a commit series.
-- description:
homepage:            https://github.com/irockasingranite/excalibur
license:             BSD-3-Clause
license-file:        LICENSE
author:              Sarah Renkhoff
maintainer:          sarah.renkhoff@gmail.com
copyright:           2025 Sarah Renkhoff
category:            Development
build-type:          Simple
extra-source-files:  README.md
                     CHANGELOG.md

flag no-integration-tests
  description:       Disable integration tests (useful for sandboxed builds)
  default:           False
  manual:            True

library
  hs-source-dirs:      src
  exposed-modules:     Checks,
                       Checks.FileCheck,
                       Checks.GlobalCheck,
                       Types,
                       Types.Base,
                       Types.Check,
                       Types.Check.FileCheck,
                       Types.Check.GlobalCheck,
                       Types.CheckReport,
                       Util,
                       Util.CheckoutCommit,
                       Util.GetChangedFiles,
                       Util.ResolveCommitRange,
                       Util.ResolvePaths,
                       Util.RunCommand,
                       Util.TempCopy,
                       Util.ExpandVariables

  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5,
                       aeson,
                       aeson-pretty,
                       bytestring,
                       directory,
                       dlist,
                       exceptions,
                       filepath,
                       Glob,
                       mtl,
                       optics,
                       scientific,
                       temporary,
                       text,
                       transformers,
                       typed-process,
                       unordered-containers,
                       yaml
  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-record-updates
                       -Wincomplete-uni-patterns
                       -Wmissing-export-lists
                       -Wmissing-home-modules
                       -Wpartial-fields
                       -Wredundant-constraints

executable excalibur
  hs-source-dirs:      app
  main-is:             Main.hs
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5,
                       aeson-pretty,
                       bytestring,
                       excalibur,
                       filepath,
                       optics,
                       optparse-applicative,
                       text,
                       yaml
  ghc-options:         -Wall
                       -Wcompat
                       -Widentities
                       -Wincomplete-record-updates
                       -Wincomplete-uni-patterns
                       -Wmissing-export-lists
                       -Wmissing-home-modules
                       -Wpartial-fields
                       -Wredundant-constraints

test-suite excalibur-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      tests
  main-is:             Main.hs
  other-modules:       CheckReportTests,
                       ExpandVariablesTests,
                       ExitCodeTests,
                       GetFinalTests,
                       ReportSummaryTests
  default-language:    Haskell2010
  ghc-options:         -Wall
  build-depends:       base >= 4.7 && < 5,
                       aeson,
                       bytestring,
                       dlist,
                       excalibur,
                       scientific,
                       tasty,
                       tasty-hunit,
                       tasty-quickcheck,
                       text,
                       yaml

test-suite excalibur-integration-tests
  type:                exitcode-stdio-1.0
  hs-source-dirs:      integration-tests
  main-is:             Main.hs
  other-modules:       GitFixture,
                       CheckoutCommitTests,
                       GetChangedFilesTests,
                       ResolveCommitRangeTests,
                       ResolvePathsTests
  default-language:    Haskell2010
  ghc-options:         -Wall
  if flag(no-integration-tests)
    buildable:         False
  else
    build-depends:     base >= 4.7 && < 5,
                       bytestring,
                       directory,
                       excalibur,
                       filepath,
                       tasty,
                       tasty-hunit,
                       temporary,
                       text
